### ISSUE TITLE
Version for Windows

### ISSUE THREAD

**Issue by ericdariel** [lgdd/liferay-cli#7]
Hello,

Many customers impose the use of Windows and it is not possible to install what we want on our machines.

Is a Windows compatible version planned ?

Or may be an alternative is possible ? Like the use of Cmder or Git bash ?

Eric.

**Comment by lgdd** [comment]
Hi @ericdariel 👋 You should have Windows versions in the [release page](https://github.com/lgdd/liferay-cli/releases) (make sure to click on "Show all assets"). You can unzip and move the .exe in any folder which should be part of the global PATH in order to be executed anywhere.

I will open different issues to explore support for [Chocolately](https://chocolatey.org/) and [Scoop](https://scoop.sh/) in order to make the installation easier.

**Comment by ericdariel** [comment]
OK, it works for Windows.

Thank you @lgdd
